/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Jeruel
 */
public class BG extends javax.swing.JFrame {

    /**
     * Creates new form BG
     */
    public BG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left_sideB = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        right_sideB = new keeptoo.KGradientPanel();
        rightPanels = new javax.swing.JTabbedPane();
        p1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        p2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        p3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        p4 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        p5 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        p6 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        LearnTrack = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_sideB.setBackground(new java.awt.Color(0, 102, 102));
        left_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 170, 50));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 50));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 50));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 50));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 50));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        left_sideB.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 50));

        jPanel1.add(left_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 610));

        right_sideB.setkEndColor(new java.awt.Color(204, 255, 255));
        right_sideB.setkStartColor(new java.awt.Color(255, 255, 255));
        right_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setkEndColor(new java.awt.Color(204, 255, 255));
        p1.setkStartColor(new java.awt.Color(255, 255, 255));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Panel 1");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab1", p1);

        p2.setkEndColor(new java.awt.Color(204, 255, 255));
        p2.setkStartColor(new java.awt.Color(255, 255, 255));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Panel 2");
        p2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab2", p2);

        p3.setkEndColor(new java.awt.Color(204, 255, 255));
        p3.setkStartColor(new java.awt.Color(255, 255, 255));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Panel 3");
        p3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab3", p3);

        p4.setkEndColor(new java.awt.Color(204, 255, 255));
        p4.setkStartColor(new java.awt.Color(255, 255, 255));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Panel 4");
        p4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab4", p4);

        p5.setkEndColor(new java.awt.Color(204, 255, 255));
        p5.setkStartColor(new java.awt.Color(255, 255, 255));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Panel 5");
        p5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab5", p5);

        p6.setkEndColor(new java.awt.Color(204, 255, 255));
        p6.setkStartColor(new java.awt.Color(255, 255, 255));
        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Panel 6");
        p6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab6", p6);

        right_sideB.add(rightPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1050, 650));

        jPanel1.add(right_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1050, 610));

        LearnTrack.setFont(LearnTrack.getFont().deriveFont(LearnTrack.getFont().getStyle() | java.awt.Font.BOLD, 36));
        LearnTrack.setForeground(new java.awt.Color(255, 255, 255));
        LearnTrack.setText("LearnTrack");
        LearnTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnTrackMouseClicked(evt);
            }
        });
        jPanel1.add(LearnTrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sicon/Untitled design.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1290, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LearnTrackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnTrackMouseClicked
      
    }//GEN-LAST:event_LearnTrackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       rightPanels.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       rightPanels.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       rightPanels.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        rightPanels.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       rightPanels.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        rightPanels.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel LearnTrack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left_sideB;
    private keeptoo.KGradientPanel p1;
    private keeptoo.KGradientPanel p2;
    private keeptoo.KGradientPanel p3;
    private keeptoo.KGradientPanel p4;
    private keeptoo.KGradientPanel p5;
    private keeptoo.KGradientPanel p6;
    private javax.swing.JTabbedPane rightPanels;
    private keeptoo.KGradientPanel right_sideB;
    // End of variables declaration//GEN-END:variables
}
