/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Jeruel
 */
public class BG extends javax.swing.JFrame {

    /**
     * Creates new form BG
     */
    public BG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left_sideB = new javax.swing.JPanel();
        rbutton1 = new finalproject.Rbutton();
        rbutton2 = new finalproject.Rbutton();
        rbutton3 = new finalproject.Rbutton();
        rbutton4 = new finalproject.Rbutton();
        rbutton5 = new finalproject.Rbutton();
        rbutton6 = new finalproject.Rbutton();
        right_sideB = new keeptoo.KGradientPanel();
        rightPanels = new javax.swing.JTabbedPane();
        p1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        p2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        p3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        p4 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        p5 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        UpLabel = new javax.swing.JPanel();
        uplabel = new javax.swing.JTabbedPane();
        lp1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lp2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lp3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lp4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lp5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lp6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        charright = new keeptoo.KGradientPanel();
        charleft = new keeptoo.KGradientPanel();
        LearnTrack = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_sideB.setBackground(new java.awt.Color(0, 102, 102));
        left_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbutton1.setBorder(null);
        rbutton1.setForeground(new java.awt.Color(255, 255, 255));
        rbutton1.setText("    Sign Out");
        rbutton1.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton1.setColor(new java.awt.Color(0, 102, 102));
        rbutton1.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton1.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton1ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 100));

        rbutton2.setBorder(null);
        rbutton2.setForeground(new java.awt.Color(255, 255, 255));
        rbutton2.setText("    My Account   ");
        rbutton2.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton2.setColor(new java.awt.Color(0, 102, 102));
        rbutton2.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton2.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton2.setHideActionText(true);
        rbutton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton2ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 100));

        rbutton3.setBorder(null);
        rbutton3.setForeground(new java.awt.Color(255, 255, 255));
        rbutton3.setText("    Information");
        rbutton3.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton3.setColor(new java.awt.Color(0, 102, 102));
        rbutton3.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton3.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton3ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 100));

        rbutton4.setBorder(null);
        rbutton4.setForeground(new java.awt.Color(255, 255, 255));
        rbutton4.setText("    Courses");
        rbutton4.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton4.setColor(new java.awt.Color(0, 102, 102));
        rbutton4.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton4.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton4ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 100));

        rbutton5.setBorder(null);
        rbutton5.setForeground(new java.awt.Color(255, 255, 255));
        rbutton5.setText("    Grades");
        rbutton5.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton5.setColor(new java.awt.Color(0, 102, 102));
        rbutton5.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton5.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton5ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 100));

        rbutton6.setBorder(null);
        rbutton6.setForeground(new java.awt.Color(255, 255, 255));
        rbutton6.setText("    Marks sheet");
        rbutton6.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton6.setColor(new java.awt.Color(0, 102, 102));
        rbutton6.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton6.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton6ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 100));

        jPanel1.add(left_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 610));

        right_sideB.setkEndColor(new java.awt.Color(204, 255, 255));
        right_sideB.setkStartColor(new java.awt.Color(255, 255, 255));
        right_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setkEndColor(new java.awt.Color(204, 255, 255));
        p1.setkStartColor(new java.awt.Color(255, 255, 255));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Panel 1");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab1", p1);

        p2.setkEndColor(new java.awt.Color(204, 255, 255));
        p2.setkStartColor(new java.awt.Color(255, 255, 255));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Panel 2");
        p2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab2", p2);

        p3.setkEndColor(new java.awt.Color(204, 255, 255));
        p3.setkStartColor(new java.awt.Color(255, 255, 255));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Panel 3");
        p3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab3", p3);

        p4.setkEndColor(new java.awt.Color(204, 255, 255));
        p4.setkStartColor(new java.awt.Color(255, 255, 255));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Panel 4");
        p4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab4", p4);

        p5.setkEndColor(new java.awt.Color(204, 255, 255));
        p5.setkStartColor(new java.awt.Color(255, 255, 255));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Panel 5");
        p5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab5", p5);

        right_sideB.add(rightPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1070, 650));

        jPanel1.add(right_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1070, 610));

        UpLabel.setBackground(new java.awt.Color(0, 153, 153));
        UpLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("My Account");
        lp1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 100));

        uplabel.addTab("tab2", lp1);

        lp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Information");
        lp2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 100));

        uplabel.addTab("tab2", lp2);

        lp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Courses");
        lp3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, 100));

        uplabel.addTab("tab2", lp3);

        lp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Grades");
        lp4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 100));

        uplabel.addTab("tab2", lp4);

        lp5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Marks Sheet");
        lp5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 100));

        uplabel.addTab("tab2", lp5);

        lp6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("My Account6");
        lp6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 100));

        uplabel.addTab("tab2", lp6);

        UpLabel.add(uplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 870, 160));

        jPanel1.add(UpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 860, 110));

        charright.setkEndColor(new java.awt.Color(0, 204, 204));
        charright.setkGradientFocus(350);
        charright.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout charrightLayout = new javax.swing.GroupLayout(charright);
        charright.setLayout(charrightLayout);
        charrightLayout.setHorizontalGroup(
            charrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        charrightLayout.setVerticalGroup(
            charrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(charright, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 50, 130));

        charleft.setkEndColor(new java.awt.Color(0, 204, 204));
        charleft.setkGradientFocus(350);
        charleft.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout charleftLayout = new javax.swing.GroupLayout(charleft);
        charleft.setLayout(charleftLayout);
        charleftLayout.setHorizontalGroup(
            charleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        charleftLayout.setVerticalGroup(
            charleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(charleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 50, 130));

        LearnTrack.setFont(LearnTrack.getFont().deriveFont(LearnTrack.getFont().getStyle() | java.awt.Font.BOLD, 36));
        LearnTrack.setForeground(new java.awt.Color(255, 255, 255));
        LearnTrack.setText("LearnTrack");
        LearnTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnTrackMouseClicked(evt);
            }
        });
        jPanel1.add(LearnTrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sicon/Untitled design.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1290, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LearnTrackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnTrackMouseClicked
      
    }//GEN-LAST:event_LearnTrackMouseClicked

    private void rbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton1ActionPerformed
        start n = new start();
        setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_rbutton1ActionPerformed

    private void rbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton2ActionPerformed
       rightPanels.setSelectedIndex(0);
        uplabel.setSelectedIndex(0);
    }//GEN-LAST:event_rbutton2ActionPerformed

    private void rbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton3ActionPerformed
        rightPanels.setSelectedIndex(1);
        uplabel.setSelectedIndex(1);
    }//GEN-LAST:event_rbutton3ActionPerformed

    private void rbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton4ActionPerformed
       rightPanels.setSelectedIndex(2);
        uplabel.setSelectedIndex(2);
    }//GEN-LAST:event_rbutton4ActionPerformed

    private void rbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton5ActionPerformed
       rightPanels.setSelectedIndex(3);
        uplabel.setSelectedIndex(3);
    }//GEN-LAST:event_rbutton5ActionPerformed

    private void rbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton6ActionPerformed
        rightPanels.setSelectedIndex(4);
        uplabel.setSelectedIndex(4);
    }//GEN-LAST:event_rbutton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel LearnTrack;
    private javax.swing.JPanel UpLabel;
    private keeptoo.KGradientPanel charleft;
    private keeptoo.KGradientPanel charright;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left_sideB;
    private javax.swing.JPanel lp1;
    private javax.swing.JPanel lp2;
    private javax.swing.JPanel lp3;
    private javax.swing.JPanel lp4;
    private javax.swing.JPanel lp5;
    private javax.swing.JPanel lp6;
    private keeptoo.KGradientPanel p1;
    private keeptoo.KGradientPanel p2;
    private keeptoo.KGradientPanel p3;
    private keeptoo.KGradientPanel p4;
    private keeptoo.KGradientPanel p5;
    private finalproject.Rbutton rbutton1;
    private finalproject.Rbutton rbutton2;
    private finalproject.Rbutton rbutton3;
    private finalproject.Rbutton rbutton4;
    private finalproject.Rbutton rbutton5;
    private finalproject.Rbutton rbutton6;
    private javax.swing.JTabbedPane rightPanels;
    private keeptoo.KGradientPanel right_sideB;
    private javax.swing.JTabbedPane uplabel;
    // End of variables declaration//GEN-END:variables
}
