/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

/**
 *
 * @author Jeruel
 */
public class BG extends javax.swing.JFrame {

    /**
     * Creates new form BG
     */
    public BG() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        left_sideB = new javax.swing.JPanel();
        rbutton1 = new finalproject.Rbutton();
        rbutton2 = new finalproject.Rbutton();
        rbutton3 = new finalproject.Rbutton();
        rbutton4 = new finalproject.Rbutton();
        rbutton5 = new finalproject.Rbutton();
        rbutton6 = new finalproject.Rbutton();
        right_sideB = new keeptoo.KGradientPanel();
        rightPanels = new javax.swing.JTabbedPane();
        p1 = new keeptoo.KGradientPanel();
        p2 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        p3 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        p4 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        p5 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        LearnTrack = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_sideB.setBackground(new java.awt.Color(0, 102, 102));
        left_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbutton1.setBorder(null);
        rbutton1.setForeground(new java.awt.Color(255, 255, 255));
        rbutton1.setText("    Sign Out");
        rbutton1.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton1.setColor(new java.awt.Color(0, 102, 102));
        rbutton1.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton1.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton1ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 100));

        rbutton2.setBorder(null);
        rbutton2.setForeground(new java.awt.Color(255, 255, 255));
        rbutton2.setText("Dashboard");
        rbutton2.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton2.setColor(new java.awt.Color(0, 102, 102));
        rbutton2.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton2.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton2.setHideActionText(true);
        rbutton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton2ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 100));

        rbutton3.setBorder(null);
        rbutton3.setForeground(new java.awt.Color(255, 255, 255));
        rbutton3.setText("Student Info");
        rbutton3.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton3.setColor(new java.awt.Color(0, 102, 102));
        rbutton3.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton3.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton3ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 100));

        rbutton4.setBorder(null);
        rbutton4.setForeground(new java.awt.Color(255, 255, 255));
        rbutton4.setText("    Courses");
        rbutton4.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton4.setColor(new java.awt.Color(0, 102, 102));
        rbutton4.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton4.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton4ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 100));

        rbutton5.setBorder(null);
        rbutton5.setForeground(new java.awt.Color(255, 255, 255));
        rbutton5.setText("    Grades");
        rbutton5.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton5.setColor(new java.awt.Color(0, 102, 102));
        rbutton5.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton5.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton5ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 100));

        rbutton6.setBorder(null);
        rbutton6.setForeground(new java.awt.Color(255, 255, 255));
        rbutton6.setText("    Marks sheet");
        rbutton6.setBorderColor(new java.awt.Color(0, 102, 102));
        rbutton6.setColor(new java.awt.Color(0, 102, 102));
        rbutton6.setColorClick(new java.awt.Color(0, 102, 102));
        rbutton6.setColorOver(new java.awt.Color(11, 135, 135));
        rbutton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbutton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutton6ActionPerformed(evt);
            }
        });
        left_sideB.add(rbutton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 100));

        jPanel1.add(left_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 610));

        right_sideB.setkEndColor(new java.awt.Color(204, 255, 255));
        right_sideB.setkStartColor(new java.awt.Color(255, 255, 255));
        right_sideB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setkEndColor(new java.awt.Color(204, 255, 255));
        p1.setkStartColor(new java.awt.Color(255, 255, 255));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rightPanels.addTab("tab1", p1);

        p2.setkEndColor(new java.awt.Color(204, 255, 255));
        p2.setkStartColor(new java.awt.Color(255, 255, 255));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Student ID");
        p2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        p2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 250, -1));

        jLabel20.setText("Name");
        p2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        p2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 250, -1));

        jLabel21.setText("Date of Birth");
        p2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        p2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 250, -1));

        jLabel22.setText("Gender");
        p2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        p2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 250, -1));

        jLabel1.setText("jLabel1");
        p2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        p2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 250, -1));

        jLabel7.setText("Phone Number");
        p2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        p2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 250, -1));

        jLabel14.setText("Address");
        p2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        p2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 250, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("BROWSE");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        p2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 430, 220));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Date of Birth", "Gender", "Email", "Phone Number", "Adress", "Photo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        p2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 530, -1));

        button1.setLabel("button1");
        p2.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 90, 30));

        button2.setLabel("ADD\n");
        p2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 90, 30));

        button3.setLabel("UPDATE");
        p2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 90, 30));

        button4.setLabel("DELETE");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        p2.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 90, 30));

        rightPanels.addTab("tab2", p2);

        p3.setkEndColor(new java.awt.Color(204, 255, 255));
        p3.setkStartColor(new java.awt.Color(255, 255, 255));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Panel 3");
        p3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab3", p3);

        p4.setkEndColor(new java.awt.Color(204, 255, 255));
        p4.setkStartColor(new java.awt.Color(255, 255, 255));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Panel 4");
        p4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab4", p4);

        p5.setkEndColor(new java.awt.Color(204, 255, 255));
        p5.setkStartColor(new java.awt.Color(255, 255, 255));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Panel 5");
        p5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 151, 141, 82));

        rightPanels.addTab("tab5", p5);

        right_sideB.add(rightPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1070, 650));

        jPanel1.add(right_sideB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1070, 610));

        LearnTrack.setFont(LearnTrack.getFont().deriveFont(LearnTrack.getFont().getStyle() | java.awt.Font.BOLD, 36));
        LearnTrack.setForeground(new java.awt.Color(255, 255, 255));
        LearnTrack.setText("LearnTrack");
        LearnTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnTrackMouseClicked(evt);
            }
        });
        jPanel1.add(LearnTrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sicon/Untitled design.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1290, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LearnTrackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnTrackMouseClicked
      
    }//GEN-LAST:event_LearnTrackMouseClicked

    private void rbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton1ActionPerformed
        start n = new start();
        setVisible(false);
        n.setVisible(true);
    }//GEN-LAST:event_rbutton1ActionPerformed

    private void rbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton2ActionPerformed
       rightPanels.setSelectedIndex(0);
       
    }//GEN-LAST:event_rbutton2ActionPerformed

    private void rbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton3ActionPerformed
        rightPanels.setSelectedIndex(1);
       
    }//GEN-LAST:event_rbutton3ActionPerformed

    private void rbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton4ActionPerformed
       rightPanels.setSelectedIndex(2);
        
    }//GEN-LAST:event_rbutton4ActionPerformed

    private void rbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton5ActionPerformed
       rightPanels.setSelectedIndex(3);
    }//GEN-LAST:event_rbutton5ActionPerformed

    private void rbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutton6ActionPerformed
        rightPanels.setSelectedIndex(4);
    }//GEN-LAST:event_rbutton6ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel LearnTrack;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel left_sideB;
    private keeptoo.KGradientPanel p1;
    private keeptoo.KGradientPanel p2;
    private keeptoo.KGradientPanel p3;
    private keeptoo.KGradientPanel p4;
    private keeptoo.KGradientPanel p5;
    private finalproject.Rbutton rbutton1;
    private finalproject.Rbutton rbutton2;
    private finalproject.Rbutton rbutton3;
    private finalproject.Rbutton rbutton4;
    private finalproject.Rbutton rbutton5;
    private finalproject.Rbutton rbutton6;
    private javax.swing.JTabbedPane rightPanels;
    private keeptoo.KGradientPanel right_sideB;
    // End of variables declaration//GEN-END:variables
}
